baseURL = "https://username.github.io/"
languageCode = "en-us"
title = "My Portfolio"
theme = "minimal"

# Enable syntax highlighting
pygmentsCodeFences = true
pygmentsUseClasses = true

# Enable emoji support
enableEmoji = true

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"
  
# Menu configuration
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Skills"
    url = "/skills/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

# Site parameters
[params]
  # Author information
  author = "{{.Name}}"
  description = "{{.Description}}"
  
  # Social links
  github = "{{.GitHub}}"
  linkedin = "{{.LinkedIn}}"
  email = "{{.Email}}"
  
  # Theme customization
  mainSections = ["projects"]
  showProjectsList = true
  showSkillsList = true
  
  # Footer text
  footerText = "Built with [Hugo](https://gohugo.io/) and [Quickfolio](https://github.com/socrabytes/quickfolio)"
