/**
 * Generator for Lynx Hugo theme
 * Converts MVPContentData to TOML configuration
 */
import { MVPContentData } from '../../types/mvp';
import { GeneratedOutput, ThemeGenerator } from '../index';

/**
 * Generate TOML configuration for Lynx Hugo theme
 */
const generateLynxConfig: ThemeGenerator = (data: MVPContentData): GeneratedOutput => {
  const { profile, links } = data;
  
  // Format links as TOML arrays
  const linksToml = links.map(link => {
    // Build each link entry
    const properties = [
      `text = "${escapeString(link.text)}"`,
      `url = "${escapeString(link.url)}"`
    ];
    
    // Add optional properties if they exist
    if (link.icon) {
      properties.push(`icon = "${escapeString(link.icon)}"`);
    }
    
    if (link.type) {
      properties.push(`type = "${escapeString(link.type)}"`);
    }
    
    // Format as TOML table
    return `[[params.links]]\n${properties.join('\n')}`;
  }).join('\n\n');
  
  // Build complete TOML configuration
  const toml = `# Lynx theme configuration for Hugo
# Auto-generated by Quickfolio

# Basic site parameters
baseURL = "https://example.com/"
languageCode = "en-us"
title = "${escapeString(profile.name)}"
theme = "lynx"

# Enable raw html in markdown
[markup.goldmark.renderer]
  unsafe = true

# Theme parameters
[params]
  # Profile settings
  name = "${escapeString(profile.name)}"
  headline = "${escapeString(profile.headline)}"
  avatar = "${escapeString(profile.avatar)}" # Place in static/
  
  # Social/contact settings
  # use 'email' for mailto: prefix
  # use 'fab' or 'fas' prefix for Font Awesome icons
  # See documentation for details
${linksToml}

# Advanced settings
[module]
  # Hugo Modules
  [[module.imports]]
    path = "github.com/jpanther/lynx"
`;

  return {
    content: toml,
    filename: 'config.toml',
    fileType: 'toml',
    mimeType: 'application/toml'
  };
};

/**
 * Helper function to escape special characters in strings for TOML
 */
function escapeString(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n');
}

export default generateLynxConfig;
